version: '3.8'

services:
  sql-server:
    image: mcr.microsoft.com/mssql/server:latest
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: redTeam123
    ports:
      - "1433:1433"
    networks:
      - backend-network
    volumes:
      - sql-server-data:/var/opt/mssql
      - ./docker_db_init.sql:/docker_db_init.sql
    # entrypoint: /bin/bash -c "/opt/mssql/bin/sqlservr & sleep 10 & /opt/mssql-tools/bin/sqlcmd -S localhost,1433 -U sa -P redTeam123 -i /docker_db_init.sql"

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "5000:8080"
    depends_on:
      - sql-server
    networks:
      - backend-network

  frontend:
    image: nginx:alpine
    volumes:
      - ./Frontend:/usr/share/nginx/html
    ports:
      - "5500:80"

volumes:
  sql-server-data:

networks:
  backend-network: