name: CD

on:
  push:
    branches:
      - main
      - dev

permissions:
  contents: read
  id-token: write

jobs:
  cd-flyway:
    name: Flyway CD
    uses: ./.github/workflows/flyway.yaml
    secrets: inherit

  cd-web:
    name: Web CD
    uses: ./.github/workflows/web-cd.yml
    secrets: inherit
